spring:
## 1.1
  profiles:    active:
    - quartz
    - jdbc
#  jpa:#    hibernate:#      ddl-auto: update
#    show-sql: true
## 1.2
  redis: 
    host: 47.102.155.32
    port: 6380
    database: 0
    password: w3i2s1ka
  
## 2.1
logging:
  config: classpath:logback-spring.xml
  level: 
    #指定包名或者类名下的日志输出级别
    com.ncstudy: trace
## 日志级别从低到高分为：TRACE < DEBUG < INFO < WARN < ERROR < FATAL 。如果设置为 WARN ，则低于 WARN 的信息都不会输出。
# private final static Logger logger = LoggerFactory.getLogger(xx.class);  

## 3.1
mybatis: 
  mapper-locations: 
    - classpath:mappers/*.xml
  type-aliases-package: com.ncstudy

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true

##自定义属性jwt
jwt:
   # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: white
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index,/login/**,/favicon.ico
