spring:
## 1.1
  profiles:
    active:
#   - quartz  ##定时器
    - jdbc    ##数据库
    - jwt
  scheduling:
    enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

## 1.2
#  redis:
#    host: 47.102.155.32
#    port: 6380
#    database: 0
#    password: w3i2s1ka
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
#    timeout: 6000
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接

  servlet:
    multipart:
      max-request-size: 80MB
      max-file-size: 80MB

## 2.1
logging:
  config: classpath:logback-spring.xml
  level: 
    #指定包名或者类名下的日志输出级别
    com.ncstudy: trace
## 日志级别从低到高分为：TRACE < DEBUG < INFO < WARN < ERROR < FATAL 。如果设置为 WARN ，则低于 WARN 的信息都不会输出。
# private final static Logger logger = LoggerFactory.getLogger(xx.class);  

## 3.1
mybatis: 
  mapper-locations: 
    - classpath:mappers/*.xml
  type-aliases-package: com.ncstudy

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true

#主要是解决springboot tomcat自带的cookie 影响操作
#这个意思是 只有这个路径携带cookie
server:
  servlet: 
    session: 
      cookie: 
        path: /nothing

#自定义 thread属性
async:
  thread:
    core_pool_size: 10
    max_pool_size: 100
    keep_alive_time: 10
    queue_capacity: 200
    thread_name_prefix: 'Async-Service-'
